# Generated by Django 3.2.13 on 2022-09-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_model_logs', '0009_alter_communicationslogentry_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationslogentry',
            options={'ordering': ['-created'], 'verbose_name': 'Communications Log Entry', 'verbose_name_plural': 'Communications Log Entries'},
        ),
    ]
