# Generated by Django 3.2.13 on 2022-08-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_model_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
    ]
