# Generated by Django 3.2.16 on 2022-11-16 01:37

import django.core.files.storage
from django.db import migrations, models
import org_model_documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('org_model_documents', '0002_alter_document_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/parkpasses/park-passes/protected_media'), upload_to=org_model_documents.models.org_model_document_path),
        ),
    ]
