# Generated by Django 3.2.13 on 2022-06-13 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('datetime_to_email', models.DateTimeField()),
                ('personal_message', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expiry', models.DateTimeField()),
                ('code', models.CharField(max_length=10)),
                ('pin', models.DecimalField(decimal_places=0, max_digits=6)),
                ('datetime_purchased', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('N', 'New'), ('D', 'Delivered'), ('ND', 'Not Delivered')], default='N', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='parkpasses.voucher')),
            ],
        ),
    ]
