# Generated by Django 3.2.13 on 2022-06-13 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('remaining_uses', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCodeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('datetime_created', models.DateTimeField()),
                ('datetime_updated', models.DateTimeField()),
                ('datetime_expiry', models.DateTimeField()),
                ('codes_to_generate', models.SmallIntegerField()),
                ('times_each_code_can_be_used', models.SmallIntegerField()),
                ('invalidated', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.AlterField(
            model_name='park',
            name='postcodes',
            field=models.ManyToManyField(blank=True, null=True, to='parkpasses.Postcode'),
        ),
        migrations.CreateModel(
            name='DiscountCodeBatchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('user', models.IntegerField()),
                ('action', models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('I', 'Invalidate')], default='C', max_length=2)),
                ('reason', models.TextField()),
                ('discount_code_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.discountcodebatch')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discountcodebatch',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('discount_amount__isnull', True), ('discount_percentage__isnull', False)), models.Q(('discount_amount__isnull', False), ('discount_percentage__isnull', True)), _connector='OR'), name='parkpasses_discountcodebatch_discount_amount_or_discount_percentage'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.discountcodebatch'),
        ),
    ]
