# Generated by Django 3.2.13 on 2022-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0002_auto_20220613_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcodebatch',
            options={'verbose_name_plural': 'Discount Code Batches'},
        ),
        migrations.RemoveField(
            model_name='discountcodebatch',
            name='number',
        ),
        migrations.AddField(
            model_name='discountcodebatch',
            name='discount_code_batch_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
