# Generated by Django 3.2.13 on 2022-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0003_auto_20220614_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcodebatch',
            options={'verbose_name': 'Discount Code Batch', 'verbose_name_plural': 'Discount Code Batches'},
        ),
        migrations.AlterField(
            model_name='discountcodebatch',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountcodebatch',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
