# Generated by Django 3.2.13 on 2022-06-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0004_auto_20220614_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(editable=False, max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('display_order', models.SmallIntegerField()),
                ('display_externally', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassTypePricingWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_expiry', models.DateTimeField(blank=True, null=True)),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.passtype')),
            ],
        ),
        migrations.CreateModel(
            name='PassTypePricingWindowOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pricing_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.passtypepricingwindow')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('pass_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_registration_1', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_registration_2', models.CharField(blank=True, max_length=10, null=True)),
                ('datetime_start', models.DateTimeField(default=False)),
                ('datetime_expiry', models.DateTimeField()),
                ('renew_automatically', models.BooleanField(default=False)),
                ('prevent_further_vehicle_updates', models.BooleanField(default=False)),
                ('park_pass_pdf', models.FilePathField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('FU', 'Future'), ('CU', 'Current'), ('EX', 'Expired'), ('CA', 'Cancelled')], max_length=2)),
                ('sold_via', models.CharField(blank=True, max_length=50, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.passtypepricingwindowoption')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.park')),
            ],
        ),
        migrations.CreateModel(
            name='DayEntryPass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parkpasses.pass',),
        ),
        migrations.CreateModel(
            name='GoldStarPass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parkpasses.pass',),
        ),
        migrations.CreateModel(
            name='HolidayPass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parkpasses.pass',),
        ),
        migrations.CreateModel(
            name='LocalParkPass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parkpasses.pass',),
        ),
    ]
