# Generated by Django 3.2.13 on 2022-06-15 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0005_dayentrypass_goldstarpass_holidaypass_localparkpass_pass_passtype_passtypepricingwindow_passtypepric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name_plural': 'Passes'},
        ),
        migrations.AlterModelOptions(
            name='passtypepricingwindow',
            options={'verbose_name': 'Pricing Window'},
        ),
        migrations.AlterModelOptions(
            name='passtypepricingwindowoption',
            options={'verbose_name': 'Duration Options'},
        ),
        migrations.AddField(
            model_name='pass',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
