# Generated by Django 3.2.13 on 2022-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0006_auto_20220615_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='park_pass_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
