# Generated by Django 3.2.13 on 2022-06-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0008_alter_pass_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_reason', models.TextField()),
                ('datetime_cancelled', models.DateTimeField(auto_now_add=True)),
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.pass')),
            ],
            options={
                'verbose_name_plural': 'Pass Cancellations',
            },
        ),
    ]
