# Generated by Django 3.2.13 on 2022-06-21 04:11

from django.db import migrations, models
import django.db.models.deletion
import parkpasses.components.passes.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parkpasses', '0009_passcancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_first_added_to', models.DateTimeField()),
                ('datetime_last_added_to', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='park',
            name='postcodes',
            field=models.ManyToManyField(blank=True, to='parkpasses.Postcode'),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='image',
            field=models.ImageField(upload_to=parkpasses.components.passes.models.pass_type_image_path),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.concession')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=191)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='parkpasses.cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.discountcode')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.voucher')),
            ],
        ),
    ]
