# Generated by Django 3.2.13 on 2022-06-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0010_auto_20220621_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='datetime_first_added_to',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
