# Generated by Django 3.2.13 on 2022-06-21 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0011_alter_cart_datetime_first_added_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='datetime_last_added_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
