# Generated by Django 3.2.13 on 2022-06-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0013_auto_20220621_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
