# Generated by Django 3.2.13 on 2022-06-21 07:50

from django.db import migrations, models
import parkpasses.components.passes.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0014_userinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to=parkpasses.components.passes.models.pass_template_image_path)),
                ('version', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name_plural': 'user Information'},
        ),
    ]
