# Generated by Django 3.2.13 on 2022-06-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0015_auto_20220621_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passtemplate',
            options={'verbose_name': 'Pass Template', 'verbose_name_plural': 'Pass Templates'},
        ),
    ]
