# Generated by Django 3.2.13 on 2022-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0016_alter_passtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtemplate',
            name='version',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
