# Generated by Django 3.2.13 on 2022-06-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0018_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helptext',
            options={'verbose_name': 'Help Text', 'verbose_name_plural': 'Help Text'},
        ),
        migrations.AlterModelOptions(
            name='passtype',
            options={'verbose_name': 'Pass Type', 'verbose_name_plural': 'Pass Types'},
        ),
        migrations.RemoveField(
            model_name='park',
            name='postcodes',
        ),
    ]
