# Generated by Django 3.2.13 on 2022-06-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0019_auto_20220623_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.park')),
                ('postcodes', models.ManyToManyField(blank=True, to='parkpasses.Postcode')),
            ],
        ),
    ]
