# Generated by Django 3.2.13 on 2022-06-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0022_auto_20220624_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.SmallIntegerField(unique=True)),
                ('display_externally', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lga',
            name='park',
        ),
        migrations.AddField(
            model_name='lga',
            name='park_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.parkgroup'),
        ),
        migrations.AddField(
            model_name='park',
            name='park_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.parkgroup'),
        ),
    ]
