# Generated by Django 3.2.13 on 2022-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0023_auto_20220624_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkgroup',
            options={'verbose_name': 'Park Group', 'verbose_name_plural': 'Park Groups'},
        ),
        migrations.AlterField(
            model_name='park',
            name='display_order',
            field=models.SmallIntegerField(),
        ),
    ]
