# Generated by Django 3.2.13 on 2022-06-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0024_auto_20220624_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='park',
            unique_together={('park_group', 'display_order')},
        ),
    ]
