# Generated by Django 3.2.13 on 2022-06-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0026_auto_20220624_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Parks ParkGroups', 'verbose_name_plural': 'Parks ParkGroups'},
        ),
    ]
