# Generated by Django 3.2.13 on 2022-06-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parkpasses', '0027_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcancellation',
            name='park_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='parkpasses.pass'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['content_type', 'object_id'], name='parkpasses__content_decd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['content_type', 'object_id'], name='parkpasses__content_ed29ee_idx'),
        ),
    ]
