# Generated by Django 3.2.13 on 2022-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0029_auto_20220629_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
