# Generated by Django 3.2.13 on 2022-07-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0032_retailergroup_retailergroupuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailergroup',
            options={'verbose_name': 'Retailer Group'},
        ),
        migrations.AlterField(
            model_name='pass',
            name='sold_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.retailergroup'),
        ),
    ]
