# Generated by Django 3.2.13 on 2022-07-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0034_auto_20220705_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='purchaser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
