# Generated by Django 3.2.13 on 2022-07-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0035_voucher_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='purchaser',
            field=models.IntegerField(),
        ),
    ]
