# Generated by Django 3.2.13 on 2022-07-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0036_alter_voucher_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
