# Generated by Django 3.2.13 on 2022-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0038_auto_20220711_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
