# Generated by Django 3.2.13 on 2022-07-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0039_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='uuid',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
