# Generated by Django 3.2.13 on 2022-07-14 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0042_auto_20220712_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='park_group',
        ),
        migrations.AddField(
            model_name='parkgroup',
            name='lgas',
            field=models.ManyToManyField(blank=True, related_name='park_group', to='parkpasses.LGA'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='parkpasses.discountcodebatch'),
        ),
    ]
