# Generated by Django 3.2.13 on 2022-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0043_auto_20220714_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkgroup',
            name='parks',
            field=models.ManyToManyField(blank=True, related_name='park_group', through='parkpasses.Member', to='parkpasses.Park'),
        ),
    ]
