# Generated by Django 3.2.13 on 2022-07-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0044_alter_parkgroup_parks'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='display_order',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
