# Generated by Django 3.2.13 on 2022-07-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0045_concession_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
