# Generated by Django 3.2.13 on 2022-07-15 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0046_passtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
