# Generated by Django 3.2.13 on 2022-07-28 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0047_alter_passtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodebatch',
            name='datetime_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
