# Generated by Django 3.2.13 on 2022-08-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0051_alter_pass_sold_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtypepricingwindowoption',
            name='pricing_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='parkpasses.passtypepricingwindow'),
        ),
    ]
