# Generated by Django 3.2.13 on 2022-08-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0052_alter_passtypepricingwindowoption_pricing_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtypepricingwindow',
            name='datetime_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passtypepricingwindow',
            name='datetime_start',
            field=models.DateField(),
        ),
    ]
