# Generated by Django 3.2.13 on 2022-08-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0053_auto_20220803_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passtypepricingwindow',
            old_name='datetime_expiry',
            new_name='date_expiry',
        ),
        migrations.RenameField(
            model_name='passtypepricingwindow',
            old_name='datetime_start',
            new_name='date_start',
        ),
    ]
