# Generated by Django 3.2.13 on 2022-08-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0054_auto_20220803_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertransaction',
            name='park_pass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_transactions', to='parkpasses.pass'),
            preserve_default=False,
        ),
    ]
