# Generated by Django 3.2.13 on 2022-08-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0055_vouchertransaction_park_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='remaining_uses',
        ),
    ]
