# Generated by Django 3.2.13 on 2022-08-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0056_remove_discountcode_remaining_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchertransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='vouchertransaction',
            name='park_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='parkpasses.pass'),
        ),
    ]
