# Generated by Django 3.2.13 on 2022-08-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0057_auto_20220808_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='parkpasses.pass')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_code_usages', to='parkpasses.discountcode')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionUsage',
            fields=[
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='parkpasses.pass')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='parkpasses.concession')),
            ],
        ),
    ]
