# Generated by Django 3.2.13 on 2022-08-09 02:15

import django.core.files.storage
from django.db import migrations, models
import django_resized.forms
import parkpasses.components.passes.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0058_concessionusage_discountcodeusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='park_pass_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/parkpasses/park-passes/protected_media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='passtemplate',
            name='template',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/parkpasses/park-passes/protected_media'), upload_to=parkpasses.components.passes.models.pass_template_file_path),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Ideal dimension for image are 300px (width) x 150px (height)', keep_meta=True, quality=99, scale=None, size=[300, 150], upload_to=parkpasses.components.passes.models.pass_type_image_path),
        ),
    ]
