# Generated by Django 3.2.13 on 2022-08-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0059_auto_20220809_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True)),
                ('answer', models.CharField(max_length=200, unique=True)),
                ('display_order', models.SmallIntegerField(null=True, unique=True)),
            ],
        ),
    ]
