# Generated by Django 3.2.13 on 2022-08-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0061_auto_20220809_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=200),
        ),
    ]
