# Generated by Django 3.2.13 on 2022-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0065_auto_20220811_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodebatch',
            name='times_each_code_can_be_used',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
