# Generated by Django 3.2.13 on 2022-08-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0066_alter_discountcodebatch_times_each_code_can_be_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodebatchvalidpasstype',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valid_pass_types', to='parkpasses.discountcodebatch'),
        ),
        migrations.AlterField(
            model_name='discountcodebatchvalidpasstype',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.passtype'),
        ),
        migrations.AlterField(
            model_name='discountcodebatchvaliduser',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valid_users', to='parkpasses.discountcodebatch'),
        ),
    ]
