# Generated by Django 3.2.13 on 2022-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0068_auto_20220819_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_reference',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='datetime_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='retailergroup',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
