# Generated by Django 3.2.13 on 2022-08-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0069_auto_20220823_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
