# Generated by Django 3.2.13 on 2022-08-24 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parkpasses', '0072_auto_20220824_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='object_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
