# Generated by Django 3.2.13 on 2022-08-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0073_auto_20220824_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_reference',
            field=models.CharField(help_text='This links the order to the matching invoice in ledger.', max_length=50, unique=True, null=False, blank=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, null=False, blank=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(help_text='This is copied from the cart to the order before the cart is deleted.', max_length=36, null=False, blank=False),
        ),
    ]
