# Generated by Django 3.2.13 on 2022-08-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0075_pass_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='park_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='discount_code_usage', serialize=False, to='parkpasses.pass'),
        ),
        migrations.AlterField(
            model_name='vouchertransaction',
            name='park_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='voucher_transaction', serialize=False, to='parkpasses.pass'),
        ),
    ]
