# Generated by Django 3.2.13 on 2022-08-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0078_alter_discountcode_discount_code_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodebatchvalidpasstype',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_pass_types', to='parkpasses.discountcodebatch'),
        ),
        migrations.AlterField(
            model_name='discountcodebatchvaliduser',
            name='discount_code_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_users', to='parkpasses.discountcodebatch'),
        ),
    ]
