# Generated by Django 3.2.13 on 2022-08-31 08:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0079_auto_20220831_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='park_pass_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/parkpasses/park-passes/protected_media'), upload_to=''),
        ),
    ]
