# Generated by Django 3.2.13 on 2022-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0080_alter_pass_park_pass_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
