# Generated by Django 3.2.13 on 2022-09-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0081_pass_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
