# Generated by Django 3.2.13 on 2022-09-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0083_auto_20220905_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='datetime_expiry',
            new_name='date_expiry',
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='datetime_start',
            new_name='date_start',
        ),
    ]
