# Generated by Django 3.2.13 on 2022-09-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0084_auto_20220905_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='concession_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.concessionusage'),
        ),
        migrations.AddField(
            model_name='concessionusage',
            name='concession_card_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.discountcodeusage'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.vouchertransaction'),
        ),
        migrations.AlterField(
            model_name='concessionusage',
            name='park_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='concession_usage', serialize=False, to='parkpasses.pass'),
        ),
    ]
