# Generated by Django 3.2.13 on 2022-09-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0085_auto_20220905_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='discount_code',
            new_name='discount_code_usage',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='voucher',
            new_name='voucher_transaction',
        ),
    ]
