# Generated by Django 3.2.13 on 2022-09-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0086_auto_20220905_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcodeusage',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='discountcodeusage',
            name='park_pass',
        ),
        migrations.RemoveField(
            model_name='vouchertransaction',
            name='park_pass',
        ),
        migrations.RemoveField(
            model_name='vouchertransaction',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='concession_usage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_code_usage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='voucher_transaction',
        ),
        migrations.DeleteModel(
            name='ConcessionUsage',
        ),
        migrations.DeleteModel(
            name='DiscountCodeUsage',
        ),
        migrations.DeleteModel(
            name='VoucherTransaction',
        ),
    ]
