# Generated by Django 3.2.13 on 2022-09-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0087_auto_20220905_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_transaction', to='parkpasses.pass')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='parkpasses.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_code_usages', to='parkpasses.discountcode')),
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discount_code_usage', to='parkpasses.pass')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_card_number', models.CharField(default='', max_length=50, unique=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='parkpasses.concession')),
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='concession_usage', to='parkpasses.pass')),
            ],
        ),
    ]
