# Generated by Django 3.2.13 on 2022-09-19 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0090_cartitem_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['datetime_created', 'object_id']},
        ),
        migrations.AlterModelOptions(
            name='passtype',
            options={'ordering': ['id'], 'verbose_name': 'Pass Type', 'verbose_name_plural': 'Pass Types'},
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pass',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('FU', 'Future'), ('CU', 'Current'), ('EX', 'Expired'), ('CA', 'Cancelled'), ('VA', 'Valid')], max_length=2, null=True),
        ),
    ]
