# Generated by Django 3.2.13 on 2022-09-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0091_auto_20220919_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_no_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_no_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailer_group', to='parkpasses.retailergroup'),
        ),
    ]
