# Generated by Django 3.2.13 on 2022-09-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0093_auto_20220919_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=10, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('processing_status', models.CharField(blank=True, choices=[('p', 'Paid'), ('U', 'Unpaid')], max_length=2, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('retailer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_retailer_group', to='parkpasses.retailergroup')),
            ],
        ),
    ]
