# Generated by Django 3.2.13 on 2022-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0095_auto_20220928_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=2, null=True),
        ),
    ]
