# Generated by Django 3.2.13 on 2022-09-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0096_alter_report_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='invoice',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
