# Generated by Django 3.2.13 on 2022-09-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0098_auto_20220929_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroup',
            name='address_line_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='address_line_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='postcode',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4, 'Australian postcodes must contain 4 digits')]),
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='state',
            field=models.CharField(choices=[('NSW', 'Western Australia'), ('VIC', 'Victoria'), ('WA', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Western Australia')], default='WA', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='suburb',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
