# Generated by Django 3.2.13 on 2022-10-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0100_auto_20220930_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroupuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
