# Generated by Django 3.2.13 on 2022-10-03 04:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0101_retailergroupuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroup',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailergroup',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retailergroupuser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 3, 4, 1, 45, 533989, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailergroupuser',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RetailerGroupInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('S', 'S'), ('UR', 'UR'), ('D', 'D'), ('A', 'A')], default='S', max_length=3)),
                ('retailer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkpasses.retailergroup')),
            ],
            options={
                'verbose_name': 'Retailer Group Invites',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
