# Generated by Django 3.2.13 on 2022-10-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0102_auto_20221003_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailergroupinvite',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Retailer Group Invite'},
        ),
        migrations.AlterField(
            model_name='retailergroupinvite',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('UR', 'User Responded'), ('D', 'Denied'), ('A', 'Approved')], default='N', max_length=3),
        ),
    ]
