# Generated by Django 3.2.13 on 2022-10-07 07:06

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkpasses', '0104_auto_20221006_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailergroupuser',
            options={'verbose_name': 'Retailer Group User'},
        ),
        migrations.AlterField(
            model_name='retailergroupinvite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='retailergroupuser',
            unique_together={('retailer_group', 'emailuser')},
        ),
    ]
