# Generated by Django 3.2.13 on 2022-10-11 07:05

from django.db import migrations
from django.utils.text import slugify

def populate_pass_type_slug_field(apps, schema_editor):
    for pass_type in apps.get_model('parkpasses.passtype').objects.all():
        pass_type.slug = slugify(pass_type.display_name)
        pass_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0108_passtype_slug'),
    ]

    operations = [
        migrations.RunPython(populate_pass_type_slug_field, migrations.RunPython.noop),        
    ]
