# Generated by Django 3.2.13 on 2022-10-11 07:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0109_auto_20221011_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='display_name', unique=True),
        ),
    ]
