# Generated by Django 3.2.13 on 2022-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0110_alter_passtype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='passtypepricingwindow',
            options={'ordering': ['pass_type', 'date_start', 'date_expiry'], 'verbose_name': 'Pricing Window'},
        ),
        migrations.AlterModelOptions(
            name='passtypepricingwindowoption',
            options={'ordering': ['pricing_window', 'price'], 'verbose_name': 'Duration Options'},
        ),
        migrations.AddField(
            model_name='pass',
            name='purchase_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
