# Generated by Django 3.2.13 on 2022-10-17 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0111_auto_20221014_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='state',
            field=models.CharField(blank=True, choices=[('NSW', 'Western Australia'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Western Australia')], default='WA', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='postcode',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4, 'Australian postcodes must contain 4 digits')]),
        ),
    ]
