# Generated by Django 3.2.13 on 2022-10-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0113_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='oracle_code',
            field=models.CharField(default='FN46V9L80', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='oracle_code',
            field=models.CharField(default='FN46V9L80', max_length=50),
        ),
    ]
