# Generated by Django 3.2.13 on 2022-10-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0114_auto_20221020_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='oracle_code',
            field=models.CharField(default='PARKPASSES_DEFAULT_ORACLE_CODE', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oracle_code',
            field=models.CharField(default='PARKPASSES_DEFAULT_ORACLE_CODE', max_length=50),
        ),
        migrations.AlterField(
            model_name='retailergroupuser',
            name='retailer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_group_users', to='parkpasses.retailergroup'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='processing_status',
            field=models.CharField(choices=[('N', 'New'), ('NDP', 'Not Delivered to Purchaser'), ('PN', 'Purchaser Notified'), ('NDR', 'Not Delivered to Recipient'), ('DR', 'Delivered to Recipient')], default='N', max_length=3),
        ),
    ]
