# Generated by Django 3.2.13 on 2022-10-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0116_retailergroupapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ['-datetime_created'], 'verbose_name_plural': 'Passes'},
        ),
    ]
