# Generated by Django 3.2.13 on 2022-10-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0117_alter_pass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='rac_member_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
