# Generated by Django 3.2.16 on 2022-10-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0118_pass_rac_member_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailergroupuser',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Retailer Group User'},
        ),
    ]
