# Generated by Django 3.2.16 on 2022-10-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0119_alter_retailergroupuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.order'),
        ),
    ]
