# Generated by Django 3.2.16 on 2022-10-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0120_pass_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='order',
        ),
    ]
