# Generated by Django 3.2.16 on 2022-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0122_auto_20221116_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
