# Generated by Django 3.2.16 on 2022-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0123_report_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
