# Generated by Django 3.2.16 on 2022-12-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0124_report_invoice_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassAutoRenewalAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_renewal_succeeded', models.BooleanField(default=False)),
                ('datetime_attempted', models.DateTimeField(auto_now_add=True)),
                ('park_pass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_renewal_attempts', to='parkpasses.pass')),
            ],
            options={
                'verbose_name_plural': 'Pass Auto Renewal Attempts',
            },
        ),
    ]
