# Generated by Django 3.2.16 on 2022-12-21 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0126_auto_20221220_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionusage',
            name='date_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 20, 1, 57, 16, 551950, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
