# Generated by Django 3.2.16 on 2022-12-22 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0127_concessionusage_date_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACDiscountUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('park_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rac_discount_usage', to='parkpasses.pass')),
            ],
        ),
    ]
