# Generated by Django 3.2.16 on 2022-12-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0128_racdiscountusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racdiscountusage',
            name='member_number',
        ),
    ]
