# Generated by Django 3.2.16 on 2022-12-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0129_remove_racdiscountusage_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rac_discount_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkpasses.racdiscountusage'),
        ),
    ]
