# Generated by Django 3.2.16 on 2022-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0130_cartitem_rac_discount_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='can_be_renewed_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
