# Generated by Django 3.2.16 on 2023-01-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0131_auto_20221223_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroup',
            name='ledger_organisation',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
