# Generated by Django 3.2.16 on 2023-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0132_retailergroup_ledger_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailergroup',
            name='ledger_organisation',
            field=models.IntegerField(null=True, unique=True, verbose_name='Ledger Organisation'),
        ),
    ]
