# Generated by Django 3.2.16 on 2023-01-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0134_auto_20230105_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
