# Generated by Django 3.2.16 on 2023-01-13 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0136_parkgroup_oracle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroup',
            name='ledger_district',
            field=models.IntegerField(default=1, verbose_name='Ledger District'),
        ),
        migrations.AlterField(
            model_name='parkgroup',
            name='oracle_code',
            field=models.CharField(default='PARKPASSES_DEFAULT_ORACLE_CODE', help_text="This oracle code is for online sales (PICA) ONLY. Don't enter regional codes here.", max_length=50),
        ),
        migrations.AlterField(
            model_name='retailergroup',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=0, default=10, help_text='IMPORTANT: Enter 0 for internal retailer groups.', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='retailergroup',
            name='oracle_code',
            field=models.CharField(blank=True, help_text='Used to allocate commission for external retailers. IMPORTANT: Leave blank for internal retailer groups.', max_length=50, null=True, unique=True),
        ),
    ]
