# Generated by Django 3.2.16 on 2023-01-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0138_rename_oracle_code_retailergroup_commission_oracle_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailergroupuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admins can invite other users to their group.'),
        ),
    ]
