# Generated by Django 3.2.16 on 2023-01-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0141_auto_20230113_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtpasstypedurationoraclecode',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailer_group', to='parkpasses.district'),
        ),
        migrations.AlterField(
            model_name='retailergroup',
            name='commission_oracle_code',
            field=models.CharField(blank=True, help_text='Used to allocate commission for external retailers.            IMPORTANT: Leave blank for internal retailer groups.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='districtpasstypedurationoraclecode',
            unique_together={('district', 'option')},
        ),
        migrations.RemoveField(
            model_name='districtpasstypedurationoraclecode',
            name='ledger_district',
        ),
    ]
