# Generated by Django 3.2.16 on 2023-01-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0142_auto_20230113_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailergroup',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailer_group', to='parkpasses.district'),
        ),
        migrations.AlterField(
            model_name='districtpasstypedurationoraclecode',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_pass_type_duration_oracle_code', to='parkpasses.district'),
        ),
    ]
