# Generated by Django 3.2.16 on 2023-01-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0144_alter_retailergroup_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtpasstypedurationoraclecode',
            options={'verbose_name': 'Oracle Code', 'verbose_name_plural': 'Oracle Codes'},
        ),
        migrations.AlterField(
            model_name='districtpasstypedurationoraclecode',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Leave blank for PICA oracle codes (online sales)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_pass_type_duration_oracle_code', to='parkpasses.district'),
        ),
    ]
