# Generated by Django 3.2.16 on 2023-01-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0145_auto_20230116_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtpasstypedurationoraclecode',
            name='oracle_code',
            field=models.CharField(help_text='The oracle code to be used for this district, pass type and pass duration.', max_length=80),
        ),
    ]
