# Generated by Django 3.2.16 on 2023-01-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0146_alter_districtpasstypedurationoraclecode_oracle_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtpasstypedurationoraclecode',
            options={'ordering': ('district__name', 'option__pricing_window__pass_type__display_order', 'option__duration'), 'verbose_name': 'Oracle Code', 'verbose_name_plural': 'Oracle Codes'},
        ),
        migrations.AddField(
            model_name='passtemplate',
            name='pass_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pass_template', to='parkpasses.passtype'),
        ),
        migrations.AlterField(
            model_name='parkgroup',
            name='oracle_code',
            field=models.CharField(default='PARKPASSES_DEFAULT_ORACLE_CODE', help_text="This oracle code is for PICA local park passes (Online Sales) ONLY. Don't enter regional codes here.", max_length=50),
        ),
    ]
