# Generated by Django 3.2.16 on 2023-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0147_auto_20230124_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtemplate',
            name='version',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='passtemplate',
            unique_together={('pass_type', 'version')},
        ),
    ]
