# Generated by Django 3.2.16 on 2023-01-31 04:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0151_alter_passtype_concession_template_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='display_name_colour',
            field=colorfield.fields.ColorField(default='#000000', help_text='Choose a colour for the pass type heading on the pass template.', image_field=None, max_length=18, samples=None),
        ),
    ]
