# Generated by Django 3.2.16 on 2023-01-31 07:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0152_passtype_display_name_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='concession_display_name_colour',
            field=colorfield.fields.ColorField(default='#000000', help_text='Choose a colour for the concession pass type heading on the pass template.', image_field=None, max_length=18, samples=None),
        ),
    ]
