# Generated by Django 3.2.16 on 2023-02-01 03:57

from django.db import migrations, models
import parkpasses.components.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0155_auto_20230201_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='basket_id',
            field=models.IntegerField(default=parkpasses.components.reports.models.get_uuid_int_six, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='invoice_reference',
            field=models.CharField(default=parkpasses.components.reports.models.get_uuid_eleven, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='order_number',
            field=models.CharField(default=parkpasses.components.reports.models.get_uuid_six, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='uuid',
            field=models.CharField(default=parkpasses.components.reports.models.get_uuid, max_length=36, unique=True),
        ),
    ]
