# Generated by Django 3.2.16 on 2023-02-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0157_auto_20230203_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtemplate',
            name='pass_type',
            field=models.ForeignKey(blank=True, help_text="When left blank this template will be used for all pass types that don't have a template specified.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pass_template', to='parkpasses.passtype'),
        ),
    ]
