# Generated by Django 3.2.16 on 2023-02-07 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0158_alter_passtemplate_pass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='oracle_code',
            field=models.CharField(blank=True, help_text='This oracle code will only be used if no district-based oracle code or local park group oracle code can be found.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='retailergroup',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Leave blank for DBCA ONLY. All other retailers (internal and external) must be assigned a district.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailer_group', to='parkpasses.district'),
        ),
    ]
