# Generated by Django 3.2.16 on 2023-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0159_auto_20230207_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='oracle_code',
            field=models.CharField(blank=True, help_text='Only to be used for pass types that are not district or park group specific. I.e. Pinjar Pass.', max_length=50, null=True, unique=True),
        ),
    ]
