# Generated by Django 3.2.17 on 2023-02-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0160_alter_passtype_oracle_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
