# Generated by Django 3.2.18 on 2023-02-24 01:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0162_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='statement',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/parkpasses/park-passes/protected_media'), upload_to=''),
        ),
    ]
