# Generated by Django 3.2.18 on 2023-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpasses', '0163_report_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='basket_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='invoice_reference',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='order_number',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='uuid',
            field=models.CharField(help_text='This is used as the booking reference for the generated ledger invoice.', max_length=36, null=True, unique=True),
        ),
    ]
